# This is a basic workflow to help you get started with Actions

name: CI-RUST-CLIPPY-NOTIFY-FULLREQ

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  #push:
  #  branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - name: Checkout code
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
        uses: actions/checkout@v4

      # Runs a single command using the runners shell
      - name: Install Rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
      - name: Build the project
        run: cargo clippy
        continue-on-error: true
        
      - name: Add reviewers if build success
        if: success()
        run: |
          curl -X POST \
            -H "Accept: application/vnd.github.v3+json" \
            -H "Authorization: token ${{ secrets.PERSONAL_ACCESS_TOKEN }}" \
            -d '{"reviewers":["HuyLeAnh", "nextneo"]}' https://api.github.com/repos/${{ github.repository }}/pulls/${{ github.event.pull_request.number }}/requested_reviewers

      - name: Send email if build fails
        if: failure()
        uses: dawidd6/action-send-mail@v3
        with:
         server_address: smtp.gmail.com
         server_port: 587
         username: ${{ secrets.HUYLE_USERNAME }}
         password: ${{ secrets.HUYLE_PASSWORD }}
         subject: Build Failed on PR ${{ github.event.pull_request.html_url }}
         body: |
             The build for PR ${{ github.event.pull_request.html_url }} has failed.
             Please check the details and fix the issues.
         to:  ${{ secrets.EMAIL_NOTIFYCATIONS }}
         from:  ${{ secrets.HUYLE_USERNAME }}